### ISSUE TITLE
Question about Hydra-GNN Data

### ISSUE THREAD

**Issue by LeonGoretzkatju** [MIT-SPARK/Hydra-GNN#1]
Hi @nathanhhughes,

Thank you so much for open-sourcing this wonderful work! Could you please share the scene graph of entire trajectory, which gets the coverage of the entire scan. I noticed that in your shared Google Drive, there are only scene graph of partial trajectory.

Thanks

**Comment by SiyiHu** [comment]
The longest trajectory in each trajectory subfolder should cover approximately the entire scan. Note that the number of Hydra segmented rooms might be much less than the number of ground-truth rooms for certain scans due to Hydra's room clustering approach. This approach tend to cluster multiple rooms if there is large open space or large windows in between. If this is a problem, you should consider using the `--repartition_rooms` flag to switch to ground-truth room segmentations.

**Comment by LeonGoretzkatju** [comment]
> The longest trajectory in each trajectory subfolder should cover approximately the entire scan. Note that the number of Hydra segmented rooms might be much less than the number of ground-truth rooms for certain scans due to Hydra's room clustering approach. This approach tend to cluster multiple rooms if there is large open space or large windows in between. If this is a problem, you should consider using the `--repartition_rooms` flag to switch to ground-truth room segmentations.

Thank you so much for your kind and helpful reply!!! My questions have been fully solved by your reply.
